### PR TITLE
Development 

### PR DESCRIPTION
**Pull request by sundayezeilo**
clone of mint.com's sign-up page ready for review.

### CODE REVIEW

**Review by imhta — APPROVED** [review]
.

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @ezeilo-su @peterrobert  , 👋 You have done a great job in this project 👏 

* [ ] Fix linter error, It seems `.stickler.yml` is empty. [Check this link](https://github.com/microverseinc/linters-config/blob/master/css)
* [ ] [Optional]  Can do fine-tuning of space and alignment of your project UI to be perfect clone of original site.

> NOTE: Collab project need to have equal number commits from both. 
----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Comment by peterrobert** [comment]
Fixed errors and properly added stickler to our project

**Comment by shshamim63** [comment]
## Status :red_circle: [!! Changes Required !!] :red_circle: 
___
Hi @ezeilo-su  and @peterrobert :wave,
Project contains readme, code looks neat and clean. Contains all the items required to decorate the page. But there are some issues that are blocking me to approve this project.
___
#### Please follow the instructions below to complete this project.
___
### :spades: [Mandatory Changes] :spades: 
___
1. The stickler is yelling some errors. If you check the error messages you will see it is talking about font-awesome-4.7.0 folder. Lets ignore this folder. Checkout this [link](https://stickler-ci.com/docs). Add this line in .stickler.yml file
```
files:
    ignore:
        - 'font-awesome-4.7.0/*'
```
___
### :clubs: [Optional Changes] :clubs: 
___
1. I just changes the background color of the form container. Andsaw that the input fields are not fully centered in their container. 
image
2. The footer of the page takes almost the full width, But the actual one seems different. 
Actual one --->
image
Your one --->
image
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by peterrobert** [comment]
Fixed the errors that were pointed out in the review. It's ready for another review

**Review by suretrust — APPROVED** [review]
Hi team, :wave: 

### Great job implementing the TSEs' suggestions. :raised_hands: Let's get this merged! :+1: 

_Good luck with your future projects and happy coding!_ :tada:

**Pull request merged**
